postgresql_database: homelab
postgresql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64333435366264323232376364666335383537393533336235346161616362333536653236333761
          3739373730373431643465666165313037663832383138310a626135333234643232376662383364
          32633366346339363435626361653431313963383365336661373861393730343338663561333363
          3263616338326431330a616237343965663239623633393230623939323961316338363837663961
          3135

additional_databases:
  k3s:
    username: k3s
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64323932646233313131643633383036656432663938613931373232393565386535376165636639
          3533306130333035613562396563393035626338643735660a363732303834313565653539643430
          31646666396137363439636231623366386134353932383838326336383933323361623936353832
          3034663966333262360a323039633338626631366439613135393538333839383134333465383131
          64366264343934363461656663643366623932613937386135393066663830373463383863643764
          3164376466396332663566303563666665653137626332613563

  hedgedoc:
    username: hedgedoc
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39356562313730346331663230663036623435333936373735336662666166313632626136333736
          3061623230643233336664336336346662303239643634350a356565396333336465316164313032
          61353561356361653237633236306539386561366430616536346233323230366639326632316432
          6339366161623563610a646565653938353334373433343138626636336231306336306562373263
          30326339343332393836663838363730396637376639636431653537383036376631336461643462
          6534323939633962623764343437643466383463336330333437
