postgresql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64333435366264323232376364666335383537393533336235346161616362333536653236333761
          3739373730373431643465666165313037663832383138310a626135333234643232376662383364
          32633366346339363435626361653431313963383365336661373861393730343338663561333363
          3263616338326431330a616237343965663239623633393230623939323961316338363837663961
          3135

postgresql_database: homelab
